server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2db/e-commerce
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  com.example.user_service.service: DEBUG

eureka:
  instance:
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  expiration-time: 86400000
  secret: Z2VuZXJhdGUteW91ci0yNTYtYml0LWp3dC1zZWNyZXQta2V5

greeting:
  message: Welcome to the Simple E-commerce.